SONADOR_OHIF_CLIENTID = 'sonador-ohif'

# Sonador OHIF Client Types
SONADOR_OHIF_SITE = 'site'
SONADOR_OHIF_APP = 'app'
SONAODR_OHIF_REDIRECT_QUERY_PARAM = 'redirect_uri'

SONADOR_CONFIG_SUPPORTED = set((SONADOR_OHIF_SITE, SONADOR_OHIF_APP))