from orthancapi import apisettings as orthanc_api
from orthancapi.apisettings import SONADOR_PERM_QUERY, SONADOR_PERM_UPLOAD, \
	SONADOR_PERM_VIEW, SONADOR_PERM_MODIFY, SONADOR_PERM_REMOVE, \
	SONADOR_PERM_COMMENT_EDIT, SONADOR_PERM_COMMENT_VIEW, SONADOR_PERM_COMMENT_ACL, \
	SONADOR_PERMS, SONADOR_SERVER_PERMS, SONADOR_RESOURCE_PERMS, \
	ORTHANC_SYSTEM, ORTHANC_INSTANCES, ORTHANC_TOOLS_FIND, ORTHANC_DICOMWEB, \
	ORTHANC_DICOMWEB_STUDIES, ORTHANC_DICOMWEB_SERIES, ORTHANC_WADO, \
	ORTHANC_RESOURCE_PATIENT, ORTHANC_RESOURCE_STUDY, ORTHANC_RESOURCE_SERIES, ORTHANC_RESOURCE_INSTANCE, \
	ORTHANC_RESOURCE_URL_PATIENT, ORTHANC_RESOURCE_URL_STUDY, ORTHANC_RESOURCE_URL_SERIES, \
	ORTHANC_RESOURCE_URL, ORTHANC_CACHE, \
	ORTHANC_CACHE_PATIENT, ORTHANC_CACHE_STUDY, ORTHANC_CACHE_SERIES, ORTHANC_CACHE_TAGS, ORTHANC_COMMENTS, \
	WILDCARD, ORTHANC_IMAGING_RESOURCES, ORTHANC_QUERY_RESOURCES

SONADOR_USERNAME = 'sonador'
SONADOR_USER_PK = -42
SONADOR_USER_LABEL = 'Sonador Web Application'
SONADOR_OHIF_CLIENTID = 'sonador-ohif'

# Sonador OHIF Client Types
SONADOR_OHIF_SITE = 'site'
SONADOR_OHIF_APP = 'app'
SONAODR_OHIF_REDIRECT_QUERY_PARAM = 'redirect_uri'

SONADOR_CONFIG_SUPPORTED = set((SONADOR_OHIF_SITE, SONADOR_OHIF_APP))


# Sonador API Output Options
SONADOR_OUTPUT_TYPE_OHIF = 'ohif'
SONADOR_OUTPUT_TYPE_QUERY_PARAM = 'output-type'


NGINX_AUTH_REQUEST_QUERY_PARAM = 'nginx-auth'


OPENID_AUTH_TOKEN_SESSION_PROVIDER_PARAM = 'openid-auth-provider'
OPENID_AUTH_TOKEN_SESSION_PARAM = 'openid-auth-token'
OPENID_AUTH_TOKEN_USER = 'openid-auth-user'
OPENID_AUTH_TOKEN_TYPE_SESSION_PARAM = 'openid-auth-token-type'
OPENID_AUTH_TOKEN_SCOPE_SESSION_PARAM = 'openid-auth-scope'