SONADOR_OHIF_CLIENTID = 'sonador-ohif'

# Sonador OHIF Client Types
SONADOR_OHIF_SITE = 'site'
SONADOR_OHIF_APP = 'app'
SONAODR_OHIF_REDIRECT_QUERY_PARAM = 'redirect_uri'

SONADOR_CONFIG_SUPPORTED = set((SONADOR_OHIF_SITE, SONADOR_OHIF_APP))


# Sonador Permissions
SONADOR_PERM_QUERY = 'query'
SONADOR_PERM_UPLOAD = 'upload'
SONADOR_PERM_VIEW = 'view'

SONADOR_PERMS = (
	SONADOR_PERM_QUERY, SONADOR_PERM_UPLOAD, SONADOR_PERM_VIEW
)

ORTHANC_INSTANCES = '/instances'
ORTHANC_TOOLS_FIND = '/tools/find'
ORTHANC_DICOMWEB_STUDIES = '/dicom-web/studies'

ORTHANC_SYSTEM = 'system'
ORTHANC_RESOURCE_PATIENT = 'patient'
ORTHANC_RESOURCE_STUDY = 'study'
ORTHANC_RESOURCE_SERIES = 'series'
ORTHANC_RESOURCE_INSTANCE = 'instance'

ORTHANC_IMAGING_RESOURCES = set((
	ORTHANC_RESOURCE_PATIENT, ORTHANC_RESOURCE_STUDY, ORTHANC_RESOURCE_SERIES, ORTHANC_RESOURCE_INSTANCE
))


# Sonador API Output Options
SONADOR_OUTPUT_TYPE_OHIF = 'ohif'
SONADOR_OUTPUT_TYPE_QUERY_PARAM = 'output-type'


NGINX_AUTH_REQUEST_QUERY_PARAM = 'nginx-auth'