Listen 8070

<VirtualHost *:8070>
ServerName imaging
ServerAlias imaging

SetEnv SONADOR_SITECONFIG "/srv/www/sonador/config/sondaor.site.config"
SetEnv DJANGO_SETTINGS_MODULE "sonador.settings"

LogLevel debug
ErrorLog /dev/stderr
TransferLog /dev/stdout

WSGIDaemonProcess imaging python-path=/srv/www/sonador/sonador:/usr/lib/python38.zip:/usr/lib/python3.8:/usr/lib/python3.8/lib-dynload:/usr/local/lib/python3.8/dist-packages:/usr/lib/python3/dist-packages threads=1 processes=10
WSGIProcessGroup imaging
WSGIApplicationGroup %{GLOBAL}
WSGIScriptAlias / /srv/www/sonador/sonador/config/wsgi-docker.py

<Directory /srv/www/sonador/sonador/config>
  <Files wsgi-docker.py>
    Require all granted
  </Files>
</Directory>

Alias /static/ /srv/www/sonador/docroot/static/
Alias /media/ /srv/www/sonador/docroot/media/

<Directory /srv/www/sonador/docroot/static>
Require all granted
</Directory>

<Directory /srv/www/sonador/docroot/media>
Require all granted
</Directory>

</VirtualHost>
