"""
Django settings for sonador project.

Generated by 'django-admin startproject' using Django 2.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os, sys, mimetypes, six, datetime, warnings
from configobj import ConfigObj
from datetime import date

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Configuration helper methods
CONFIG_POSITIVE = ('true', 'yes', 'affirmative', 'yup', 'y', '1', 't')
def config_str2bool(boolstr):
    if isinstance(boolstr, bool): return boolstr
    if isinstance(boolstr, six.string_types):
        return boolstr.lower() in CONFIG_POSITIVE
    return False

# Retrieve site.config path
if not os.path.exists(os.environ.get('SONADOR_SITECONFIG', '')):
    raise NameError('Unable to locate a valid site.config file for the project. '
        + 'Please check the "SONADOR_SITECONFIG" environment variable.')

PROJECT_ROOT = BASE_DIR
PROJECT_CONFIGURATION_ROOT = os.path.join(PROJECT_ROOT, 'sonador')
RESOURCE_ROOT = os.path.join(PROJECT_ROOT, 'resources')

# Load site.config settings
siteconfig = ConfigObj(os.environ.get('SONADOR_SITECONFIG'))
SETTINGS_DIR = os.path.dirname(os.environ.get('SONADOR_SITECONFIG'))

# Add lib and apps directories to the path
sys.path.append(os.path.join(BASE_DIR, 'lib'))
sys.path.append(os.path.join(BASE_DIR, 'apps'))
if not SETTINGS_DIR in sys.path:
    sys.path.append(SETTINGS_DIR)

# Import guru helpers
import guru.apisettings as gapicodes
import messages.apisettings as mapicodes
import secure.apisettings as sapicodes



# Site Configuration Settings

# Core site configuration settings
siteconfig_site = siteconfig.get('Site-Config', {})
SITE_ID = int(siteconfig_site.get('SITE_ID', 0))
SITE_NAME = siteconfig_site.get('SITE_NAME')
SITE_URL = SITE_NAME
SECRET_KEY = siteconfig_site.get('SECRET_KEY')
INTERNAL_IPS = tuple(siteconfig_site.get('INTERNAL_IPS', ('127.0.0.1',) ))
ALLOWED_HOSTS = tuple(siteconfig_site.get('ALLOWED_HOSTS', []))
VERIFY_SSL_CONNECTIONS = config_str2bool(siteconfig_site.get('VERIFY_SSL_CONNECTIONS', True))



# Remote Request Settings
HTTP_REQUEST_TIMEOUT_DEFAULT = siteconfig_site.get(
    'HTTP_REQUEST_TIMEOUT_DEFAULT', gapicodes.HTTP_REQUEST_TIMEOUT_DEFAULT)



# Logging
LOG_LEVEL = siteconfig_site.get('LOG_LEVEL', mapicodes.API_LOG_INFO.upper())
LOG_LEVEL_CONSOLE = LOG_LEVEL
LOG_FILE = siteconfig_site.get('LOG_FILE')


MANAGEMENT_LOG_FORMAT = siteconfig_site.get('MANAGEMENT_LOG_FORMAT', gapicodes.MANAGEMENT_LOG_FORMAT)
APPLICATION_LOG_FORMAT = siteconfig_site.get('APPLICATION_LOG_FORMAT', gapicodes.APPLICATION_LOG_FORMAT)

siteconfig_logging = siteconfig.get('Logging', {})

LOG_CONFIG_HANDLERS = siteconfig_logging.get('Handlers', {})
LOG_CONFIG_LOGGERS = siteconfig_logging.get('Loggers', {})

if not isinstance(LOG_CONFIG_HANDLERS, dict):
    raise TypeError('Invalid logging handlers configuration (type: %s): %r'
        % (str(type(LOG_CONFIG_HANDLERS)), LOG_CONFIG_HANDLERS))
if not isinstance(LOG_CONFIG_LOGGERS, dict):
    raise TypeError('Invalid logging loggers configuration (type: %s): %r'
        % (str(type(LOG_CONFIG_LOGGERS)), LOG_CONFIG_LOGGERS))


# Convert propagate values of Loggers to boolean
for lname, lconfig in six.iteritems(LOG_CONFIG_LOGGERS):
    lconfig['propagate'] = config_str2bool(lconfig.get('propagate'))

# Log Rotation
LOG_HISTORY_DAYS_DEFAULT = 18*30
LOG_HISTORY_DAYS = int(siteconfig_site.get('LOG_HISTORY_DAYS', LOG_HISTORY_DAYS_DEFAULT))



# Database Settings
DATABASES = siteconfig.get('Databases', {})

for dbname, dbdata in six.iteritems(DATABASES):

        # Set CONN_MAX_AGE type for database entries
        if dbdata.get('CONN_MAX_AGE') and not isinstance(dbdata.get('CONN_MAX_AGE'), int):
                try: dbdata['CONN_MAX_AGE'] = int(dbdata.get('CONN_MAX_AGE'))
                except Exception as err:
                    raise ValueError('Invalid CONN_MAX_AGE value: %r' % dbdata.get('CONN_MAX_AGE'))


# Database Migrations
MIGRATION_MODULES = siteconfig.get('Database-Migrations', {})


# Database Routers (Production)
DATABASE_ROUTERS = siteconfig_site.get('DATABASE_ROUTERS', [])



# Site Connection Settings
siteconfig_connection = siteconfig.get('Site-Connection', {})
SITE_CONNECT_SCHEME = siteconfig_connection.get('SITE_CONNECT_SCHEME')
SITE_CONNECT_PORT = siteconfig_connection.get('SITE_CONNECT_PORT')
SITE_CONNECT_SCHEME_DEVEL = siteconfig_connection.get('SITE_CONNECT_SCHEME_DEVEL')
SITE_CONNECT_PORT_DEVEL = siteconfig_connection.get('SITE_CONNECT_PORT_DEVEL')
BASE_URL = siteconfig_connection.get('BASE_URL')



# Runtime settings
DEBUG = True
template_debug = DEBUG




# Timezone and Language Settings

# Enable time zone support for forms and templates
# Database values are stored in UTC
siteconfig_locale = siteconfig.get('Localization', {})
USE_TZ = True

# Use UTC timezone by default
TIME_ZONE = siteconfig_locale.get('TIME_ZONE', 'UTC')

# Language Settings
LANGUAGE_CODE = siteconfig_locale.get('LANGUAGE_CODE', 'en-us')
MACHINE_DEFAULT_LANGUAGE_ABBR = siteconfig_locale.get('MACHINE_DEFAULT_LANGUAGE_ABBR', 'en')
MACHINE_DEFAULT_LANGUAGE_TERRITORY_ABBR = siteconfig_locale.get('MACHINE_DEFAULT_LANGUAGE_TERRITORY_ABBR', 'US')
LANGUAGES = (
    ('en', 'English'),
)
USE_I18N = True
USE_L10N = True



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Oak-Tree Base Applications
    'guru',             # Oak-Tree Base Application
    'secure',           # Secure Access API: access IDs/secret keys, access tokens
    'sassycss',         # Helper utilities for managing styles and artsy resources
    'microservices',    # Base classes for managing integration with remote systems

    # Sonador
    'visionaire',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sonador.urls'


sonador_template_context_processors = [
    'django.template.context_processors.debug',
    'django.template.context_processors.request',
    'django.contrib.auth.context_processors.auth',
    'django.contrib.messages.context_processors.messages',
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(PROJECT_CONFIGURATION_ROOT, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': sonador_template_context_processors,
        },
    },
]

WSGI_APPLICATION = 'sonador.wsgi.application'


# SCSS Resource Paths
SCSS_RESOURCE_PATHS = (
    os.path.join(PROJECT_ROOT, 'lib', 'guru', 'styles'),
    os.path.join(PROJECT_ROOT, 'styles'),
)
SCSS_STATIC_ROOT = os.path.join(PROJECT_CONFIGURATION_ROOT, 'static', 'css')
if not os.path.exists(SCSS_STATIC_ROOT):
    os.makedirs(SCSS_STATIC_ROOT)




# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

STATICFILES_DIRS = [
    os.path.join(PROJECT_CONFIGURATION_ROOT, 'static'),
]



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'


# Authentication Settings
siteconfig_auth = siteconfig.get('Authentication', {})


# Site Redirect Settings
LOGOUT_REDIRECT_URL = siteconfig_auth.get('LOGOUT_REDIRECT_URL', '/')

