from .base import *
from .base import LOG_CONFIG_HANDLERS, LOG_CONFIG_LOGGERS, LOG_HISTORY_DAYS_DEFAULT, \
	LOG_HISTORY_DAYS, LOG_LEVEL, LOG_LEVEL_CONSOLE, LOG_FILE, \
	MANAGEMENT_LOG_FORMAT, APPLICATION_LOG_FORMAT
from .production import *
from .production import LOGGING, LOGGING_HANDLERS, LOGGING_LOGGERS


# Turn on debugging for Python code and templates
DEBUG = True
TEMPLATES[0]['OPTIONS']['debug'] = DEBUG


# Connection settings
SITE_CONNECT_SCHEME = SITE_CONNECT_SCHEME_DEVEL
SITE_CONNECT_PORT = SITE_CONNECT_PORT_DEVEL

