'''	Constants and values used by the Orthanc API module
'''

# Orthanc Imaging Server Resources
IMAGING_SERVER_RESOURCE_PATIENT = 'Patient'
IMAGING_SERVER_RESOURCE_STUDY = 'Study'
IMAGING_SERVER_RESOURCE_SERIES = 'Series'
IMAGING_SERVER_RESOURCE_IMAGE = 'Instance'
IMAGING_SERVER_RESOURCE_REPORT = 'Report'

IMAGING_SERVER_RESOURCES = set((
	IMAGING_SERVER_RESOURCE_PATIENT, 
	IMAGING_SERVER_RESOURCE_STUDY, 
	IMAGING_SERVER_RESOURCE_SERIES, 
	IMAGING_SERVER_RESOURCE_IMAGE
))

IMAGING_SERVER_LAST_UPDATE = 'LastUpdate'
IMAGING_SERVER_MODIFIED = 'Modified'
IMAGING_SERVER_STABLE = 'IsStable'
IMAGING_SERVER_MAINDICOM = 'MainDicomTags'
IMAGING_SERVER_PATIENT_MAINDICOM = 'PatientMainDicomTags'
IMAGING_SERVER_DICOMTAGS_SIGNATURE = 'MainDicomTagsSignature'
IMAGING_SERVER_PARENT_PATIENT = 'ParentPatient'
IMAGING_SERVER_PARENT_STUDY = 'ParentStudy'
IMAGING_SERVER_REQUESTED_TAGS = 'RequestedTags'


# Sonador Permissions
SONADOR_PERM_QUERY = 'query'
SONADOR_PERM_UPLOAD = 'upload'
SONADOR_PERM_VIEW = 'view'
SONADOR_PERM_MODIFY = 'modify'
SONADOR_PERM_REMOVE = 'remove'
SONADOR_PERM_COMMENT_EDIT = 'comment_edit'
SONADOR_PERM_COMMENT_VIEW = 'comment_view'
SONADOR_PERM_COMMENT_ACL = 'acl'


SONADOR_SERVER_PERMS = (SONADOR_PERM_QUERY, SONADOR_PERM_UPLOAD)
SONADOR_RESOURCE_PERMS = (
	SONADOR_PERM_VIEW, SONADOR_PERM_MODIFY, SONADOR_PERM_REMOVE,
	SONADOR_PERM_COMMENT_EDIT, SONADOR_PERM_COMMENT_VIEW, SONADOR_PERM_COMMENT_ACL\
)

SONADOR_PERMS = SONADOR_SERVER_PERMS + SONADOR_RESOURCE_PERMS

ORTHANC_SYSTEM = 'system'

ORTHANC_INSTANCES = '/instances'
ORTHANC_TOOLS_FIND = '/tools/find'
ORTHANC_TOOLS_FIND_SECURE = '/tools/secure-find'
ORTHANC_DICOMWEB = '/dicom-web'
ORTHANC_DICOMWEB_STUDIES = '%s/studies' % ORTHANC_DICOMWEB
ORTHANC_DICOMWEB_SERIES = '%s/series' % ORTHANC_DICOMWEB
ORTHANC_WADO = '/wado'

ORTHANC_RESOURCE_PATIENT = IMAGING_SERVER_RESOURCE_PATIENT.lower()
ORTHANC_RESOURCE_STUDY = IMAGING_SERVER_RESOURCE_STUDY.lower()
ORTHANC_RESOURCE_SERIES = IMAGING_SERVER_RESOURCE_SERIES.lower()
ORTHANC_RESOURCE_INSTANCE = IMAGING_SERVER_RESOURCE_IMAGE.lower()

ORTHANC_RESOURCE_URL_PATIENT = '/patients'
ORTHANC_RESOURCE_URL_STUDY = '/studies'
ORTHANC_RESOURCE_URL_SERIES = '/series'

ORTHANC_RESOURCE_URL = {
	IMAGING_SERVER_RESOURCE_PATIENT.lower(): ORTHANC_RESOURCE_URL_PATIENT,
	IMAGING_SERVER_RESOURCE_STUDY.lower(): ORTHANC_RESOURCE_URL_STUDY,
	IMAGING_SERVER_RESOURCE_SERIES.lower(): ORTHANC_RESOURCE_URL_SERIES,
}

ORTHANC_CACHE = '/cache'
ORTHANC_CACHE_PATIENT = '%s/patient' % ORTHANC_CACHE
ORTHANC_CACHE_STUDY = '%s/studies' % ORTHANC_CACHE
ORTHANC_CACHE_SERIES = '%s/series' % ORTHANC_CACHE
ORTHANC_CACHE_TAGS = '%s/dcm-tags' % ORTHANC_CACHE

ORTHANC_COMMENTS = 'comments'


WILDCARD = '*'


# "View" resource endpoints
ORTHANC_IMAGING_RESOURCES = set((
	ORTHANC_RESOURCE_PATIENT, ORTHANC_RESOURCE_STUDY, ORTHANC_RESOURCE_SERIES, ORTHANC_RESOURCE_INSTANCE
))

# "Query" resource endpoints
ORTHANC_QUERY_RESOURCES = set((
	ORTHANC_CACHE_TAGS,
))



ORTHANC_STATIC_RESOURCES = ('css', 'js', 'ico', 'woff2', 'ttf', 'gif')
ORTHANC_OHIF_ROOT = '/ohif'
ORTHANC_OHIF_VIEWER = '%s/viewer' % ORTHANC_OHIF_ROOT
ORTHANC_OHIF_ASSETS = '%s/assets/' % ORTHANC_OHIF_ROOT